/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { OrbitControls, PerspectiveCamera, Sky, Stage, useGLTF } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import React, { Suspense } from "react";

export default function JadeBangle(props) {
  const { scene } = useGLTF("/777_jade_bangle.glb");
  return (
    <Suspense>
      <Canvas>
        <PerspectiveCamera makeDefault position={[0, 0, 3]}/>
        <OrbitControls enablePan enableZoom enableRotate />
        <Sky
          distance={450000}
          sunPosition={[0, 1, 1]}
          inclination={0}
          azimuth={0.25}
        />
        <Stage>
          <group dispose={null}>
            <primitive scale={[1, 1, 1]} object={scene} />
          </group>
        </Stage>
      </Canvas>
    </Suspense>
  );
}

useGLTF.preload("/777_jade_bangle.glb");

